# Generated by Django 4.1.2 on 2023-03-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('star', models.FloatField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('movies_and_ratings', models.CharField(max_length=5000)),
            ],
        ),
    ]
