# Generated by Django 4.1.2 on 2023-03-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualUsersMovie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('movies', models.ManyToManyField(to='movie.movie')),
            ],
        ),
    ]
