# Generated by Django 4.1.2 on 2023-03-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_virtualusersmovie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualusersmovie',
            name='movies',
            field=models.ManyToManyField(blank=True, to='movie.movie'),
        ),
    ]
