# Generated by Django 4.1.2 on 2023-03-13 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_virtualusersmovie_movies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VirtualUsersMovie',
        ),
    ]
