# Generated by Django 4.1.2 on 2023-03-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='movies_and_ratings',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
