# Generated by Django 4.1.2 on 2023-04-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_usergroup_delete_rating_movie_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='movies_rated',
            field=models.ManyToManyField(null=True, to='movie.movie'),
        ),
    ]
