# Generated by Django 4.1.2 on 2023-04-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_alter_usergroup_movies_rated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='movies_rated',
            field=models.ManyToManyField(blank=True, null=True, to='movie.movie'),
        ),
    ]
