# Generated by Django 4.1.2 on 2023-04-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_alter_usergroup_movies_rated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='average_rating',
            new_name='sum_of_rating',
        ),
        migrations.AddField(
            model_name='movie',
            name='no_of_user_rated',
            field=models.IntegerField(default=0),
        ),
    ]
