# Generated by Django 4.1.2 on 2023-04-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_rename_average_rating_movie_sum_of_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=5000)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='links',
            field=models.ManyToManyField(to='movie.link'),
        ),
    ]
