# Generated by Django 4.1.2 on 2023-04-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_link_movie_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=17),
        ),
        migrations.AddField(
            model_name='user',
            name='email_address',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
